name: Auto PR dev → main

on:
  push:
    branches: ["dev"]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  autopr:
    runs-on: ubuntu-latest
    steps:
      - name: Open PR dev → main if not exists
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const base = "main";
            const branchRef = context.ref || "";
            const branch = branchRef.replace("refs/heads/", "");
            if (branch !== "dev") {
              core.info(`Not on dev branch: ${branch}`);
              return;
            }
            // check if an open PR from dev->main already exists
            const head = `${owner}:${branch}`;
            const { data: pulls } = await github.rest.pulls.list({
              owner, repo, state: "open", head, base, per_page: 1
            });
            if (pulls.length > 0) {
              core.info(`PR already open: #${pulls[0].number} ${pulls[0].html_url}`);
              return;
            }
            const title = `Auto PR: ${branch} → ${base}`;
            const body = [
              `Авто‑PR из \`${branch}\` в \`${base}\`. Открыт автоматически при push.`,
              "",
              `- Репозиторий: ${owner}/${repo}`,
              `- Коммит: ${context.sha}`
            ].join("\n");
            const { data: pr } = await github.rest.pulls.create({
              owner, repo, head: branch, base, title, body, maintainer_can_modify: true, draft: false
            });
            core.notice(`Opened PR #${pr.number}: ${pr.html_url}`);
